### ISSUE TITLE
Instructions for Linux

### ISSUE THREAD

**Issue by oscarlevin** [bartsnapp/ximeraLatex#2]
As a GitHub n00b, I had not assigned a ssh key to my linux machine.  Thus when I tired to follow your instructions for cloning the repository in linux I got an error.  I was able to clone the repository using the https link instead (and eventually got myself a ssh key following the instructions on github, and cloning via ssh worked fine then).

I don't know if it is worth worrying about this for folks with linux, but if you are going to include instructions for getting git on linux, you might as well supply a link to the instructions for setting ssh up.

**Comment by bartsnapp** [comment]
Hi,

I like using the SSH key *better* than https .. maybe both should be given

**Comment by mthomas7** [comment]
Good idea - I can put both in now.
